export const games = [
  {
    id: 1,
    round: "J1",
    date: "2026-08-08",
    time: "20:30",
    homeTeam: "Est. Amadora",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/estrela-amadora.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 2,
    round: "J2",
    date: "2026-08-14",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Vitória SC",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/vitoria-sc.png",
  },
  {
    id: 3,
    round: "J3",
    date: "2026-08-23",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "FC Alverca",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/alverca.png",
  },
  {
    id: 4,
    round: "J4",
    date: "2026-08-30",
    time: "20:30",
    homeTeam: "Rio Ave",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/rio-ave.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 5,
    round: "J5",
    date: "2026-09-06",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Nacional",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/nacional.png",
  },
  {
    id: 6,
    round: "J6",
    date: "2026-09-13",
    time: "20:30",
    homeTeam: "FC Famalicão",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/famalicao.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 7,
    round: "J7",
    date: "2026-09-20",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "FC Arouca",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/arouca.png",
  },
  {
    id: 8,
    round: "J8",
    date: "2026-10-11",
    time: "20:30",
    homeTeam: "SC Braga",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/braga.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 9,
    round: "J9",
    date: "2026-10-25",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Académico",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/academico.png",
  },
  {
    id: 10,
    round: "J10",
    date: "2026-11-01",
    time: "20:30",
    homeTeam: "Casa Pia AC",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/casa-pia.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 11,
    round: "J11",
    date: "2026-11-08",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Moreirense",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/moreirense.png",
  },
  {
    id: 12,
    round: "J12",
    date: "2026-11-29",
    time: "20:30",
    homeTeam: "FC Porto",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/porto.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 13,
    round: "J13",
    date: "2026-12-06",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Marítimo",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/maritimo.png",
  },
  {
    id: 14,
    round: "J14",
    date: "2026-12-13",
    time: "20:30",
    homeTeam: "Gil Vicente",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/gil-vicente.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 15,
    round: "J15",
    date: "2026-12-20",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Estoril Praia",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/estoril.png",
  },
  {
    id: 16,
    round: "J16",
    date: "2026-12-27",
    time: "20:30",
    homeTeam: "Benfica",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/benfica.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 17,
    round: "J17",
    date: "2027-01-10",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Santa Clara",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/santa-clara.png",
  },
  {
    id: 18,
    round: "J18",
    date: "2027-01-17",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Est. Amadora",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/estrela-amadora.png",
  },
  {
    id: 19,
    round: "J19",
    date: "2027-01-24",
    time: "20:30",
    homeTeam: "Vitória SC",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/vitoria-sc.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 20,
    round: "J20",
    date: "2027-01-31",
    time: "20:30",
    homeTeam: "FC Alverca",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/alverca.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 21,
    round: "J21",
    date: "2027-02-07",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Rio Ave",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/rio-ave.png",
  },
  {
    id: 22,
    round: "J22",
    date: "2027-02-14",
    time: "20:30",
    homeTeam: "Nacional",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/nacional.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 23,
    round: "J23",
    date: "2027-02-21",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "FC Famalicão",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/famalicao.png",
  },
  {
    id: 24,
    round: "J24",
    date: "2027-02-28",
    time: "20:30",
    homeTeam: "FC Arouca",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/arouca.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 25,
    round: "J25",
    date: "2027-03-07",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "SC Braga",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/braga.png",
  },
  {
    id: 26,
    round: "J26",
    date: "2027-03-14",
    time: "20:30",
    homeTeam: "Académico",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/academico.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 27,
    round: "J27",
    date: "2027-03-21",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Casa Pia AC",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/casa-pia.png",
  },
  {
    id: 28,
    round: "J28",
    date: "2027-04-04",
    time: "20:30",
    homeTeam: "Moreirense",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/moreirense.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 29,
    round: "J29",
    date: "2027-04-11",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "FC Porto",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/porto.png",
  },
  {
    id: 30,
    round: "J30",
    date: "2027-04-18",
    time: "20:30",
    homeTeam: "Marítimo",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/maritimo.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 31,
    round: "J31",
    date: "2027-04-25",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Gil Vicente",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/gil-vicente.png",
  },
  {
    id: 32,
    round: "J32",
    date: "2027-05-02",
    time: "20:30",
    homeTeam: "Estoril Praia",
    awayTeam: "Sporting CP",
    homeLogo: "/logos/estoril.png",
    awayLogo: "/logos/sporting.png",
  },
  {
    id: 33,
    round: "J33",
    date: "2027-05-09",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Benfica",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/benfica.png",
  },
  {
    id: 34,
    round: "J34",
    date: "2027-05-16",
    time: "20:30",
    homeTeam: "Sporting CP",
    awayTeam: "Santa Clara",
    homeLogo: "/logos/sporting.png",
    awayLogo: "/logos/santa-clara.png",
  },
];